trigger:
  branches:
    include:
      - none
  paths:
    include:
      - "Infrastructure/**"

variables:
  - group: Common
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Job_1
        displayName: "Build and publish artifact"
        steps:
          - checkout: self
          - task: CopyFiles@2
            inputs:
              SourceFolder: "$(Build.Repository.LocalPath)"
              Contents: infrastructure/templates/*'
              TargetFolder: "$(Build.Repository.LocalPath)/infrastructure/templates"
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.Repository.LocalPath)/infrastructure/templates"
              artifact: templates
              publishLocation: "pipeline"

  - template: deploy.yaml
    parameters:
      EnvironmentPostFix: development
      ServiceConnection: $(sc.connection)
      Location: $(location)
      AppName: $(appName)
